### PR TITLE
Feature/todo UI

### PR DESCRIPTION
**Pull request by seoha376**
## ✅ Pull Request Checklist

- [x] PR Title: [Feature/Fix/Refactor...] Brief summary of the work (branch name) #IssueNumber
- [x] Verify that the commit messages are appropriate.
- [x] Confirm that the request is made to the correct branch.
- [ ] Add Assignees and Labels.
- [ ] If there is someone who needs to review specific details, add them as a Reviewer.
- [ ] After the PR is approved, delete the branch.

<br/>

## 🔄 Changes

This PR does the following:

- Did this!
- Also did that!

<br/>

## 📎 Reason for Changes

- These changes were made for the following reasons!

<br/>

closes: #IssueNumber

## 👨🏻‍💻 Test Checklist

- Performed these tests!

<br/>

## 📌 Additional Changes or Important Notes

<br/>

### CODE REVIEW

**Review by seoha376 — COMMENTED** [review]
Hmm...

**Comment by hajinki** [comment]
good!!

**Review by hajinki — APPROVED** [review]
good achievement!

**Comment by yen2i** [comment]
I think it is really good!!

**Pull request merged**
